### ISSUE TITLE
请教你有舌诊图片的数据

### ISSUE THREAD

**Issue by gcgongchao** [miaozasanynoe/---#1]
请问老铁，在哪里获取舌诊的数据？

**Comment by charfole** [comment]
同问~请问发issue的兄弟知道在哪里拿到或者爬取数据集吗？

**Comment by gcgongchao** [comment]
@charfole  目前不知，后来没看这个了，不过有个思路可以获取数据，不过费时。可以采购彩色版本的舌诊相关书籍，里面有舌诊图片和资料。不过这样的数据肯定是有干扰的。

**Comment by charfole** [comment]
好的，感谢您的思路~
